name: Shadows
main: info.hawksharbor.Shadows.Shadows
version: @VERSION@
author: ToppleTheNun
description: Dynamic vanishing - never before seen!

commands:
    shadows:
        description: Shows shadows subcommands.
        usage: /<command>
        aliases: [shadow, shad, ss]
permissions:
    shadows.*:
        description: All Shadows permissions.
        children:
            shadows.user.disappear: true
            shadows.command.verbose: true
            shadows.command.debug: true
            shadows.command.light: true
            shadows.admin.immunity: true
            shadows.admin.see: true
            shadows.admin.info: true
    shadows.user.*:
        description: User Shadows permissions.
        children:
            shadows.user.disappear: true
    shadows.command.*:
        description: Shadows commands.
        children:
            shadows.command.verbose: true
            shadows.command.debug: true
            shadows.command.light: true
    shadows.admin.*:
        description: Admin permissions.
        children:
            shadows.admin.immunity: true
            shadows.admin.see: true
            shadows.admin.info: true
    shadows.user.disappear:
        description: Allows player to disappear and reappear.
        default: op
    shadows.command.verbose:
        description: Allows player to use the shadows verbose subcommand.
        default: op
    shadows.command.debug:
        description: Allows player to use the shadows debug subcommand.
        default: op
    shadows.command.light:
        description: Allows player to use the shadows light subcommand.
    shadows.admin.immunity:
        description: Player won't receive damage while invisible.
        default: op
    shadows.admin.see:
        description: Player can see all vanished players.
        default: op
    shadows.admin.info:
        description: Player can see info with shadows command.
        default: op